### ISSUE TITLE
INCREDIBLE: Anyone else encounters crashes when PE players ioin?

### ISSUE THREAD

**Issue by thebigsmileXD** [thebigsmileXD/BossBarAPI#10]
For me the server crashes due to 'still xxx bytes unread' if a PE player comes on the server

**Comment by solo5star** [comment]
well, i never seen crashes

**Comment by thebigsmileXD** [comment]
Sounds great.

**Comment by HarryMyStick** [comment]
hey dan you can lend me your microsoft account to download mcpe win10? plz...

**Comment by thebigsmileXD** [comment]
Hell no

**Comment by KairusDarkSeeker** [comment]
Lmao
