### ISSUE TITLE
Undefined variable: eid 

### ISSUE THREAD

**Issue by Driesboy** [thebigsmileXD/BossBarAPI#11]
Notice: Undefined variable: eid in C:\Users\pc\Desktop\V5\Lobby\plugins\BossBarAPI-master\src\xenialdan\BossBarAPI\API.php on line 154

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/BossAnnouncement/commit/31b4e9fd8376e0a56b39840ee57612e899355b1c
