### ISSUE TITLE
Missing argument 2

### ISSUE THREAD

**Issue by Driesboy** [thebigsmileXD/BossBarAPI#12]
Warning: Missing argument 2 for xenialdan\BossBarAPI\API::playerMove(), called in C:\Users\pc\Desktop\V5\Lobby\plugins\BossAnnouncement-master\src\xenialdan\BossAnnouncement\Main.php on line 56 and defined in C:\Users\pc\Desktop\V5\Lobby\plugins\BossBarAPI-master\src\xenialdan\BossBarAPI\API.php on line 149

**Comment by PikyCZ** [comment]
i have too problem 
Warning: Missing argument 2 for xenialdan\BossBarAPI\API::playerMove(), called in phar:///hlserver/27495/plugins/BossAnnouncement.phar/src/xenialdan/BossAnnouncement/Main.php on line 56 and defined in phar:///hlserver/27495/plugins/BossBarAPI.phar/src/xenialdan/BossBarAPI/API.php on line 149

Notice: Undefined variable: eid in phar:///hlserver/27495/plugins/BossBarAPI.phar/src/xenialdan/BossBarAPI/API.php on line 154

**Comment by thebigsmileXD** [comment]
I dont have it anymore it was fixed once

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/BossAnnouncement/commit/31b4e9fd8376e0a56b39840ee57612e899355b1c
