### ISSUE TITLE
The top bar

### ISSUE THREAD

**Issue by flaxues** [thebigsmileXD/BossBarAPI#13]
The top bar keeps moving to the left.. Which is kinda annoying. Is there a way to fix this?

**Comment by thebigsmileXD** [comment]
moving to the left? you mean like actually going left or just how full the bar is? maybe the wither is in the void would be weird though

**Comment by flaxues** [comment]
The headbar is moving to the left with each message. and resets when the cycle resets.

**Comment by thebigsmileXD** [comment]
Whats your configuration? Its a feature

**Comment by flaxues** [comment]
---
# Example Look #
# First 3 seconds: #
#
# Welcome to the WolvesFortress.de Server, {player}!
# ================----------------------------------
#        The best server, the best minigames!
#
# Next 3 seconds: #
#
# Welcome to the WolvesFortress.de Server, {player}!
# =================================-----------------
#      Visit our website: wolvesfortress.de!
#
# If you don't define the top message, the changing messages will be displayed there. #

#         Changing messages are up here :P
# ==================================================
head-message: "{GOLD}{BOLD}>{RESET} {GREEN}HillCraft {AQUA}PE {GOLD}{BOLD}<{RESET}"
# Changing messages are here
# To set the percentage of the bar add {number%} before the message!
# Otherwise it takes the percentage that was there before.
# Example for a 25% filled: "{25%}This is a quarter filled bar >>"
changing-messages:
 - "{0%}{GOLD}{BOLD}>{RESET} {AQUA}Remember to vote daily with {DARK_AQUA}{BOLD}/vote {GOLD}{BOLD}<{RESET}"
 - "{25%}{GOLD}{BOLD}>{RESET} {BOLD}{RED}vote: {RESET}www.hillcraft.cf/vote {GOLD}{BOLD}<{RESET}"
 - "{50%}{GOLD}{BOLD}>{RESET} {BOLD}{RED}shop: {RESET}www.hillcraft.cf/shop {GOLD}{BOLD}<{RESET}"
 - "{75%}{GOLD}{BOLD}>{RESET} {BOLD}{DARK_AQUA}Twitter: {RESET}twitter.com/HillCraftMCPE {GOLD}{BOLD}<{RESET}"
 - "{100%}{GOLD}{BOLD}>{RESET} {BOLD}{DARK_PURPLE} Discord: {RESET}https://discord.me/hillcraft {GOLD}{BOLD}<{RESET}"
# How fast the messages switch in seconds
change-speed: 5
...

**Comment by thebigsmileXD** [comment]
it should go to the right though. 
> # To set the percentage of the bar add {number%} before the message!
> # Otherwise it takes the percentage that was there before.
> # Example for a 25% filled: "{25%}This is a quarter filled bar >>"

You could just set the % all to 0 or 100

**Comment by flaxues** [comment]
https://youtu.be/DmhKjWMemFc

look at the bar

**Comment by thebigsmileXD** [comment]
Ah i see. Seems like it depends on the with of the bottom bar. Bölsme mojang. it should be centered..

**Comment by thebigsmileXD** [comment]
Mojang fault :(
