### ISSUE TITLE
Error - Player Join Event

### ISSUE THREAD

**Issue by Kenner-G** [thebigsmileXD/BossBarAPI#14]
Hello there!

Whenever a player joins our server, I get the following error: 
> `02:46:50 | Elywing thread:CRITICAL > "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'BossAnnouncement v1.0.1': Undefined class constant 'DATA_LEAD_HOLDER_EID' on xenialdan\BossAnnouncement\Main 02:46:50 | Elywing thread:CRITICAL > Error: "Undefined class constant 'DATA_LEAD_HOLDER_EID'" (EXCEPTION) in "/plugins/BossBarAPI/src/xenialdan/BossBarAPI/API" at line 36`

**To reproduce the error:**

1. Join a server with the plugins BossBarAPI and BossAnnouncement enabled.
2. Review the console and you will receive the error.

**More information:**
Server software - Elywing.
Server information: Ubuntu 14.04

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/BossBarTest/issues/4

**Comment by thebigsmileXD** [comment]
Fault if Elwing.
