### ISSUE TITLE
Showing the BossBar on a specific world

### ISSUE THREAD

**Issue by kpwnh** [thebigsmileXD/BossBarAPI#15]
Hello.

I want to show the BossBar on one specific world, also, at the whole world, i mean, you walk very far of the spawn point, the bossbar disappears.

Thanks.

**Comment by thebigsmileXD** [comment]
Fix for 'The boss bar disappears': 'only-spawn: false'

Great idea, maybe a per-world config like in my other plugins.

**Comment by KillerXtream** [comment]
Oh! Thank you

**Comment by thebigsmileXD** [comment]
Just fixed so it actually shows in every world (text doesn't stop updating)

world only option coming later

**Comment by thebigsmileXD** [comment]
Done i guess
