### ISSUE TITLE
Does not work in MCPE 1.0

### ISSUE THREAD

**Issue by DeathRaven359** [thebigsmileXD/BossBarAPI#16]
BossBar fails to show in the latest version of MCPE.

**Comment by thebigsmileXD** [comment]
@DeathRaven359 are you sure its running? /pl
Could be that the packet changed. I'll check

**Comment by ApexDevelops** [comment]
Works for me

**Comment by SuperDude36** [comment]
Same for me

**Comment by SuperDude36** [comment]
You have to use the pull request. All it says is "Loading.." So I just changed loading to the message I want it to say :P. But You can't have changing messages. Please help!

**Comment by SuperDude36** [comment]
Shock..... Instead of laughing can you help xD?
