### ISSUE TITLE
How to use tihis api.

### ISSUE THREAD

**Issue by Frago9876543210** [thebigsmileXD/BossBarAPI#2]
Open main.php and edit this.
<br>
1. add imports
<code>
use pocketmine\event\player\PlayerJoinEvent;<p>
use xenialdan\BossBarAPI\API;
</code>
<hr>
2. add variable api in Enable
<code>
$this->api = new API();
</code>
<hr>
3. use api function:
<br>
	public function setBar(PlayerJoinEvent $e){<br>
		$eid = mt_rand(999, 9999999);<br>
		$this->api->sendBossBarToPlayer($e->getPlayer(), $eid, "todo");<br>
		$this->api->setPercentage(100, $eid);<br>
	}<br>

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/BossBarTest

**Comment by thebigsmileXD** [comment]
Static functions.

**Comment by thebigsmileXD** [comment]
And thats not how you call events.

**Comment by Thunder33345** [comment]
shouldent this be in wiki not issue?

**Comment by thebigsmileXD** [comment]
@Thunder33345 what. Intelligable
