### ISSUE TITLE
Armor

### ISSUE THREAD

**Issue by SuperDude36** [thebigsmileXD/BossBarAPI#20]
Whenever you use a sword or anything with armor on it breaks INCREDIBLY fast

**Comment by XShockinFireX** [comment]
@SuperDude36 I'm pretty sure this doesn't correlate to this plugin...

**Comment by SuperDude36** [comment]
Nope. It does. When I removed BossAnnouce and BossBarAPI the glitch stopped

**Comment by thebigsmileXD** [comment]
Swords can't have armor on it. Its also DEFINITELY not related to the plugin.

**Comment by SuperDude36** [comment]
Well ok, I won't use this plugin any more... I'll try on a test server...

**Comment by SuperDude36** [comment]
AHA!!!I figured it out. This plugin isn't compatible with my MobStacker! Makes no sense but I tried it....

[StackMobsSRC-4.phar.zip](https://github.com/thebigsmileXD/BossBarAPI/files/706075/StackMobsSRC-4.phar.zip)
[StackMobs.zip](https://github.com/thebigsmileXD/BossBarAPI/files/706076/StackMobs.zip)

**Comment by thebigsmileXD** [comment]
it sure makes sense, MobStacker replaces the wither i guess.

**Comment by SuperDude36** [comment]
Ugh... now I need a new mob stacker :/

**Comment by Thunder33345** [comment]
well dont your mob stacker have some sort of whitelist?
like dont stack withers as ex?

**Comment by SuperDude36** [comment]
no... its a cheap one off of YT
