### ISSUE TITLE
Increase entity count for each player

### ISSUE THREAD

**Issue by MyNameIsTriXz** [thebigsmileXD/BossBarAPI#21]
Since the wither is spawned to a player and is not registered by the server, it is useless to increase the entity count each time it is spawned. It would be better if you'd define a public variable $id which increases the entity id count once it gets initialized and is used as the id everytime you spawn the wither to a player, instead of using an increased entity count for each player.

**Comment by thebigsmileXD** [comment]
If you would actually know how to read code, you would know that it DOES NOT.
