### ISSUE TITLE
Protocol changes of pmmp

### ISSUE THREAD

**Issue by SalmonDE** [thebigsmileXD/BossBarAPI#24]
The namespace changes of pmmp make this plugin crash on the newest version.
pocketmine\network\protocol -> pocketmine\network\mcpe\protocol\

Edit:
It seems like there must be more done than just fixing the namespaces to make this plugin work again for pmmp.

**Comment by thebigsmileXD** [comment]
Version untested.

**Comment by thebigsmileXD** [comment]
Fixed + tested
