### ISSUE TITLE
Please Update it! It's in API 2.2.2 Please update it!

### ISSUE THREAD

**Issue by CyanCreeper** [thebigsmileXD/BossBarAPI#28]
Please update this. I really need this for my server. Thanks!
![capture](https://user-images.githubusercontent.com/29900872/27975879-196dc3d2-6332-11e7-88e2-26a179a59ae3.PNG)

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/BossBarAPI/blob/master/plugin.yml#L4 How about updating your server?
