### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by CyanCreeper** [thebigsmileXD/BossBarAPI#30]
09.07 17:31:17 [Server] Server thread/CRITICAL ClassNotFoundException: "Class pocketmine\network\protocol\AddEntityPacket not found" (EXCEPTION) in "src/spl/BaseClassLoader" at line 144
09.07 17:31:17 [Server] Server thread/CRITICAL Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'BossAnnouncement v1.0.2': Class pocketmine\network\protocol\AddEntityPacket not found on xenialdan\BossAnnouncement\Main

NO BOSS BAR POPS ON WHEN A PLAYER JOINS!

**Comment by thebigsmileXD** [comment]
Software outdated.
