### ISSUE TITLE
NEW Console error

### ISSUE THREAD

**Issue by CyanCreeper** [thebigsmileXD/BossBarAPI#31]
09.07 17:38:29 [Server] Server thread/INFO Disabling BossBarAPI v2.2.2
09.07 17:38:29 [Server] Server thread/CRITICAL ClassNotFoundException: "Class pocketmine\network\protocol\DataPacket not found" (EXCEPTION) in "src/spl/BaseClassLoader" at line 144

PLEASE FIX

**Comment by thebigsmileXD** [comment]
Banned for spamming.
