### ISSUE TITLE
Create BossBar to xyz

### ISSUE THREAD

**Issue by opkiler22789** [thebigsmileXD/BossBarAPI#8]
whether it is possible to cause BossBar on xyz? whether this function?

**Comment by EpicSteve33** [comment]
You could add that yourself a good way of doing it probably is

` if($player->distance(new Vector3($x, $y, $z)) > 5){`

if you want to do an area of `5` or you could change 5 to a larger number

or you could just get the players xyz and activate the bar if they enter that xyz

**Comment by thebigsmileXD** [comment]
@opkiler22789 Sorry, what? I do not understand your english.

**Comment by thebigsmileXD** [comment]
Oh i understand due to @EpicSteve33 

So you want it only on certain areas.

You could use 
```php
	public function onPlayerMove(PlayerMoveEvent $event){
if($player->distance(new Vector3($x, $y, $z)) > 5){
		if($this->eid === null){
			$this->eid = API::addBossBar([$ev->getPlayer()], 'ThisIsYourTextHere');
		}
		else{
			API::sendBossBarToPlayer($ev->getPlayer(), $this->eid, 'ThisIsYourTextHere');
		}

/*THIS ONLY IF ITS A BIG AREA!!!*/
		$pk = API::playerMove($event->getPlayer());
		unset($event);
/*BIG AREA END*/
}
else{
			API::removeBossBar([$ev->getPlayer()], $this->eid);
}
	}
```

**Comment by EpicSteve33** [comment]
@thebigsmileXD he want to know if its possible to activate the boss bar on a certain xyz and I think an area would be better than just one xyz because seems dumb to do it that way I prefer an area but I think it would be cool to implement this into your plugin somehow

**Comment by thebigsmileXD** [comment]
not into my plugin, because its the API. A plugin should extend it. Also i tested the code above and it works.

**Comment by opkiler22789** [comment]
@thebigsmileXD error: Call to a member function distance()
you mean by "$player->distance"?

**Comment by thebigsmileXD** [comment]
Thats not the full error, give the full line please. On null?
i guess
change the first lines to:
```php
	public function onPlayerMove(PlayerMoveEvent $event){
$player=$event->getPlayer();
if($player->distance(new Vector3($x, $y, $z)) > 5){
```

**Comment by thebigsmileXD** [comment]
PlayerMove directly in the API is deprecated now. Also the queswtion was answered
