### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by VCraftMCPE** [thebigsmileXD/BossBarAPI#9]
It won't work error Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'BossBarTest v1.0.0': Undefined class constant 'DATA_FLAG_NOAI' on xenialdan\BossBarTest\Main

**Comment by thebigsmileXD** [comment]
Oh, what software? I still have to change it to NO_AI @thebigsmileXD #TODO

**Comment by thebigsmileXD** [comment]
Fixed

**Comment by VCraftMCPE** [comment]
still dosent work lol

**Comment by ApexDevelops** [comment]
Works fine
